Run echo "NVIDIA 드라이버 및 CUDA Toolkit 설치 중..."
NVIDIA 드라이버 및 CUDA Toolkit 설치 중...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.jYiSVYUMgF/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/keys/NVIDIA-GPG-KEY
gpg: requesting key from 'https://developer.download.nvidia.com/compute/cuda/keys/NVIDIA-GPG-KEY'
gpg: WARNING: unable to fetch URI https://developer.download.nvidia.com/compute/cuda/keys/NVIDIA-GPG-KEY: No data
deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu22.04/x86_64/ /
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://packages.microsoft.com/repos/azure-cli jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Ign:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu22.04/x86_64  InRelease
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2180 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [372 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1177 kB]
Err:13 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu22.04/x86_64  Release
  404  Not Found [IP: 152.195.19.142 443]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [287 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [28.9 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1956 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [313 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [957 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [203 kB]
Get:19 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [15.7 kB]
Get:20 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [40.2 kB]
Get:21 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [173 kB]
Reading package lists...
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu22.04/x86_64  Release' does not have a Release file.
Error: Process completed with exit code 100.
