name: Python Stock Analysis and Discord Webhook

on:
  schedule:
    - cron: '0 7 * * *'  # 매일 07:00 UTC에 실행 (KST 16:00)

  workflow_dispatch:  # 수동 실행을 위한 설정

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 리포지토리의 코드를 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 사용할 Python 버전 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip 업그레이드
          pip install -r requirements.txt  # requirements.txt에 명시된 패키지 설치

      - name: Run stock analysis
        run: |
          python stock_analysis.py  # 주식 분석 스크립트 실행

      - name: Send results to Discord
        run: |
          python discord_webhook.py  # 디스코드 웹훅 스크립트 실행
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # 시크릿으로 웹훅 URL 사용
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # 시크릿으로 OpenAI API 키 사용

      - name: Upload log file
        uses: actions/upload-artifact@v3  # 로그 파일 업로드
        with:
          name: stock-analysis-log  # 업로드할 아티팩트의 이름
          path: logs/stock_analysis.log  # logs 디렉토리의 로그 파일 경로 (필요한 경우)
