name: Python application

on:
  workflow_dispatch:   # 수동 실행을 위한 설정
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Python 3.8로 설정

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -U conda  # Conda 설치
        conda env create -f requirements.yml  # Conda 환경 생성
        conda activate stock_analysis_env  # 환경 활성화
        conda install pip  # Conda 환경에 pip 설치

    - name: Run script
      run: |
        python stock_analysis.py  # 본인의 파일 이름으로 변경
