name: Run Stock Analysis and Discord Webhook

on:
  schedule:
    - cron: '0 7 * * *'  # 매일 16:00 KST에 실행 (UTC 07:00)
  workflow_dispatch:  # 수동 실행을 위한 설정

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 리포지토리의 코드를 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 사용할 Python 버전 설정

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-nanum fonts-dejavu  # 한글 글꼴 설치

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip 업그레이드
          pip install -r requirements.txt  # requirements.txt에 명시된 패키지 설치

      - name: Run Stock Analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # OpenAI API 키 시크릿 사용
        run: |
          echo "주식 분석 스크립트 실행 중..."  # 실행 시작 메시지
          python stock_analysis.py json_results/input_data.json json_results/top_50_stocks.json  # 입력 및 출력 파일 경로 전달
          echo "주식 분석 스크립트 실행 완료."  # 실행 완료 메시지

      - name: Run Discord Webhook Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Discord 웹훅 URL 시크릿 사용
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # OpenAI API 키 시크릿 사용
        run: |
          echo "Discord 웹훅 스크립트 실행 중..."  # 실행 시작 메시지
          python discord_webhook.py json_results/top_50_stocks.json  # JSON 파일 경로를 인수로 전달
          echo "Discord 웹훅 스크립트 실행 완료."  # 실행 완료 메시지

      - name: Upload log file
        uses: actions/upload-artifact@v3  # 로그 파일 업로드
        with:
          name: discord-webhook-log  # 업로드할 아티팩트의 이름
          path: logs/discord_webhook.log  # 로그 파일 경로 (필요시 수정)

      - name: Get Korean Time
        run: |
          echo "한국 시간: $(node -e 'const getKoreaTime = () => { const now = new Date(); const diffConfig = now.getTimezoneOffset() * 60 * 1000; const diffKorea = 9 * 60 * 60 * 1000; const koreaTime = new Date(now.getTime() + diffConfig + diffKorea); return koreaTime.getFullYear() + \"년 \" + (koreaTime.getMonth() + 1) + \"월 \" + koreaTime.getDate() + \"일 \" + koreaTime.getHours() + \"시 \"; }; console.log(getKoreaTime());')"
