name: Python application

on:
  workflow_dispatch:   # 수동 실행을 위한 설정
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: $HOME/miniconda/pkgs
        key: ${{ runner.os }}-conda-${{ hashFiles('requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Set up Conda environment
      run: |
        conda create -n stock_analysis_env python=3.8 -y
        conda run -n stock_analysis_env pip install -U pip setuptools

    - name: Install dependencies
      run: |
        conda run -n stock_analysis_env conda env update -f requirements.yml

    - name: Run script
      run: |
        conda run -n stock_analysis_env python stock_analysis.py  # 본인의 파일 이름으로 변경
