name: Python Stock Analysis

on:
  push:
  workflow_dispatch:  # 수동 실행을 위한 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 원하는 Python 버전

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 필요한 패키지 설치

      - name: Run stock analysis script
        run: python stock_analysis.py  # 주식 분석 스크립트 실행

      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          name: stock-analysis-log
          path: stock_analysis.log  # 로그 파일 업로드
