name: Python application

on: 
  push:
    branches:
      - main  # main 브랜치에 푸시할 때만 실행
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 사용할 Python 버전

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # requirements.txt에서 종속성 설치

    - name: Run stock analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Secrets에서 API 키를 환경 변수로 설정
      run: |
        python stock_analysis.py  # 주식 분석 스크립트 실행
