name: Python application

on:
  workflow_dispatch:   # 수동 실행을 위한 설정
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 사용할 Python 버전
    
    - name: Install dependencies
      run: |
        pip install requests pandas openai  # 필요한 패키지 설치

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # 환경 변수로 API 키 설정
      run: |
        python stock_analysis.py  # 본인의 파일 이름으로 변경
