name: Python Stock Analysis and Discord Bot

on:
  workflow_dispatch:  # 수동 실행을 위한 설정

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 리포지토리의 코드를 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 사용할 Python 버전 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip 업그레이드
          pip install -r requirements.txt  # requirements.txt에 명시된 패키지 설치

      - name: Run stock analysis script
        run: python stock_analysis.py  # 주식 분석 스크립트 실행

      - name: Run Discord bot
        run: python bot.py  # 디스코드 봇 스크립트 실행
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # GitHub Secrets에서 가져온 봇 토큰
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # GitHub Secrets에서 가져온 OpenAI API 키

      - name: Upload log file
        uses: actions/upload-artifact@v3  # 로그 파일 업로드
        with:
          name: stock-analysis-log  # 업로드할 아티팩트의 이름
          path: logs/stock_analysis.log  # logs 디렉토리의 로그 파일 경로
